"""ERPy public API."""

from .analysis import Analysis
from .artifact_anchor import POST_ARTIFACT_ZERO, artifact_envelope, detect_post_artifact_anchor, detect_zero_time_artifact
from .bad_channels import (
    ArtifactResponseReport,
    BadChannelReport,
    DEFAULT_HARD_ARTIFACT_REASONS,
    detect_artifactual_responses,
    detect_bad_channels,
    reject_artifactual_responses,
    reject_bad_channels,
    response_artifact_summary,
)
from .bids import BIDSImportResult, discover_bids_ieeg, import_bids_project
from .dataloader import DataLoader
from .crp import CRPConfig, CRPResult, compare_crp_across_stim_sites, run_crp, run_crp_all
from .crp_energy import (
    CRP_ENERGY_DETECTOR_VERSION,
    CRPEnergyConfig,
    CRPEnergyResult,
    FixedWindowReproducibilityResult,
    fixed_window_reproducibility_sign_flip_test,
    paired_log_rms_sign_flip_test,
    run_crp_energy_array,
)
from .epochs import Epochs, EpochsCore, UnsafeLegacyEpochMetadataError
from .erp_detection import (
    ALL_METHODS,
    DETECTOR_DEFINITIONS,
    DETECTOR_QUANTITY_COLUMNS,
    DETECTOR_REFERENCES,
    PRIMARY_CRITERION,
    detect,
)
from .events import EventDetectionError, Events, create_events_from_binary_series, create_events_from_timestamps
from .events import detect_events_from_artifacts, evoked_to_datetime, process_events_for_session
from .facade import AnalysisResult, EpochsResult, Patient, Recording, Session, Study
from .graph_metrics import (
    bidirectional_edge_summary,
    compute_dynamic_graph_metrics,
    dynamic_target_distribution_metrics,
    evoked_graph_metric_timecourse,
    evoked_response_edges_over_time,
    opportunity_conditioned_reciprocity,
    weighted_directed_node_metrics,
)
from .inference import (
    BootstrapInterval,
    SignFlipResult,
    exact_sign_flip_test,
    fdr_bh,
    hierarchical_bootstrap_interval,
)
from .pipeline import Pipeline, UnsafeLegacyProcessedMetadataError
from .connectivity import (
    canonicalize_connectivity_edges,
    coherence_matrix_from_dataframe,
    connectivity_matrix_from_dataframe,
    dataframe_time_window,
    granger_causality_matrix_from_dataframe,
    multitaper_coherence_matrices_from_dataframe,
    mutual_information_matrix_from_dataframe,
    plv_matrix_from_dataframe,
    post_stim_rest_window,
)
from .coordinates import complete_contact_coordinates
from .response_metrics import zscore_metric_within_stim
from .spectral import (
    DEFAULT_BANDS,
    ComodulogramResult,
    EpochsSpectral,
    PACResult,
    PLVResult,
    SpectralConfig,
    TFRResult,
    band_power,
    coherence_matrix,
    compute_ersp,
    compute_psd,
    compute_tfr,
    granger_causality_matrix,
    inter_trial_phase_coherence,
    mutual_information_matrix,
    phase_amplitude_comodulogram,
    phase_amplitude_coupling,
    phase_locking_value,
    phase_phase_coupling,
    phase_phase_matrix,
    plv_matrix,
)
from .storage import load_continuous_npz, resample_continuous, save_continuous_npz
from .traveling_waves import (
    DEFAULT_SCAFFOLD_PATTERN,
    estimate_latency_gradient,
    latency_distance_permutation_test,
    latency_gradient_permutation_test,
    latency_wavefront_table,
    scaffold_region_mask,
)
from .waveform_qc import (
    WaveformAudit,
    audit_waveforms,
    common_mode_recovery_diagnostic,
)

__version__ = "1.0.0"
# This developer-maintained checkpoint is shared by every installation with
# the same numerical and QC semantics. It is not a participant identifier, a
# local release-record label, or a network destination. Bump it only when
# numerical analysis results or QC semantics change.
CHECKPOINT_COMPATIBILITY_ID = "415a636abd5b9a28"

__all__ = [
    "Analysis",
    "AnalysisResult",
    "ArtifactResponseReport",
    "BIDSImportResult",
    "BadChannelReport",
    "BootstrapInterval",
    "ComodulogramResult",
    "CRPConfig",
    "CRPEnergyConfig",
    "CRPEnergyResult",
    "CRP_ENERGY_DETECTOR_VERSION",
    "CRPResult",
    "FixedWindowReproducibilityResult",
    "CHECKPOINT_COMPATIBILITY_ID",
    "DEFAULT_BANDS",
    "DEFAULT_HARD_ARTIFACT_REASONS",
    "DEFAULT_SCAFFOLD_PATTERN",
    "DataLoader",
    "DETECTOR_DEFINITIONS",
    "DETECTOR_QUANTITY_COLUMNS",
    "DETECTOR_REFERENCES",
    "Epochs",
    "EpochsCore",
    "EpochsResult",
    "EpochsSpectral",
    "EventDetectionError",
    "Events",
    "PACResult",
    "PLVResult",
    "Pipeline",
    "PRIMARY_CRITERION",
    "Patient",
    "POST_ARTIFACT_ZERO",
    "Recording",
    "Session",
    "SignFlipResult",
    "SpectralConfig",
    "Study",
    "TFRResult",
    "UnsafeLegacyEpochMetadataError",
    "UnsafeLegacyProcessedMetadataError",
    "ALL_METHODS",
    "WaveformAudit",
    "__version__",
    "band_power",
    "bidirectional_edge_summary",
    "canonicalize_connectivity_edges",
    "coherence_matrix",
    "coherence_matrix_from_dataframe",
    "connectivity_matrix_from_dataframe",
    "complete_contact_coordinates",
    "compute_ersp",
    "compute_psd",
    "compute_tfr",
    "common_mode_recovery_diagnostic",
    "compare_crp_across_stim_sites",
    "create_events_from_binary_series",
    "create_events_from_timestamps",
    "compute_dynamic_graph_metrics",
    "dynamic_target_distribution_metrics",
    "dataframe_time_window",
    "estimate_latency_gradient",
    "latency_distance_permutation_test",
    "latency_gradient_permutation_test",
    "exact_sign_flip_test",
    "fdr_bh",
    "fixed_window_reproducibility_sign_flip_test",
    "granger_causality_matrix",
    "granger_causality_matrix_from_dataframe",
    "inter_trial_phase_coherence",
    "hierarchical_bootstrap_interval",
    "load_continuous_npz",
    "mutual_information_matrix",
    "mutual_information_matrix_from_dataframe",
    "multitaper_coherence_matrices_from_dataframe",
    "opportunity_conditioned_reciprocity",
    "phase_amplitude_comodulogram",
    "phase_amplitude_coupling",
    "phase_locking_value",
    "paired_log_rms_sign_flip_test",
    "phase_phase_coupling",
    "phase_phase_matrix",
    "plv_matrix_from_dataframe",
    "plv_matrix",
    "post_stim_rest_window",
    "run_crp",
    "run_crp_all",
    "run_crp_energy_array",
    "artifact_envelope",
    "audit_waveforms",
    "discover_bids_ieeg",
    "detect",
    "detect_artifactual_responses",
    "detect_bad_channels",
    "detect_events_from_artifacts",
    "detect_post_artifact_anchor",
    "detect_zero_time_artifact",
    "evoked_graph_metric_timecourse",
    "evoked_response_edges_over_time",
    "evoked_to_datetime",
    "import_bids_project",
    "process_events_for_session",
    "reject_artifactual_responses",
    "reject_bad_channels",
    "response_artifact_summary",
    "resample_continuous",
    "save_continuous_npz",
    "latency_wavefront_table",
    "scaffold_region_mask",
    "zscore_metric_within_stim",
    "weighted_directed_node_metrics",
]
