rawdata_path: ./raw
procdata_path: ./procdata
rawdata_meta_path: ./metadata/raw_metadata.csv
stim_meta_path: ./metadata/stim_metadata.csv
elec_meta_path: ./metadata/electrode_metadata.csv
event_path:
python_path:
session_ids:
  EXAMPLE_PATIENT:
    - A
